updated the role to support Tomcat 8, added the tasks for terminatei, test and cleanup

diff --git a/templates/QFlow.sh.j2 b/templates/QFlow.sh.j2
--- a/templates/QFlow.sh.j2
+++ b/templates/QFlow.sh.j2
@@ -56,7 +56,16 @@ case $1 in
 'start')
 
     if [ -r $QBDIR/flow/${ID}/Flow.json ]; then
+        FLOW_CFG=$QBDIR/flow/${ID}/Flow.json
+    elif [ -r $QBDIR/flow/${ID}/Default.json ]; then
+        FLOW_CFG=$QBDIR/flow/${ID}/Default.json
+    else
+        echo "Master Configuration file is not found"
+        exit 1
+    fi
 
+
+    if [ "$FLOW_CFG" != "" ]; then
         QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
 
         ## gracefully shutdown the QBroker flow first
@@ -67,7 +76,7 @@ case $1 in
         yourid=`/usr/bin/id | /bin/awk '{print $1}'`
         if [ "$yourid" = "$myid" ]
         then
-            $JAVA -DQF_${ID} -DLoggerName=QFlow_${ID} ${JAVA_OPTS} $DAEMON -I $QBDIR/flow/${ID}/Flow.json >> $LOGDIR/QFlow_${ID}.out 2>&1 &
+            $JAVA -DQF_${ID} -DLoggerName=QFlow_${ID} ${JAVA_OPTS} $DAEMON -I $FLOW_CFG >> $LOGDIR/QFlow_${ID}.out 2>&1 &
         else
             echo "It can only be started by the owner: $OWNER"
             exit 1
@@ -77,33 +86,30 @@ case $1 in
 
 'stop')
 
-    if [ -r $QBDIR/flow/${ID}/Flow.json ]; then
+    QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
 
+    ## gracefully shutdown the QBroker flow first
+    test "$QFLOW_PIDS" != "" && /bin/kill $QFLOW_PIDS
+
+    for retry in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
+    do
         QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
+        test "$QFLOW_PIDS" = "" && break 
+        /bin/sleep 3
+    done
 
-        ## gracefully shutdown the QBroker flow first
-        test "$QFLOW_PIDS" != "" && /bin/kill $QFLOW_PIDS
+    QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
 
-        for retry in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
-        do
-            QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
-            test "$QFLOW_PIDS" = "" && break 
-            /bin/sleep 3
-        done
+    ## confirm the shutdown is successful
+    if [ "$QFLOW_PIDS" != "" ]
+    then
+         /bin/kill $QFLOW_PIDS
 
-        QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
+         /bin/sleep 3
+         QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
 
-        ## confirm the shutdown is successful
-        if [ "$QFLOW_PIDS" != "" ]
-        then
-             /bin/kill $QFLOW_PIDS
-
-             /bin/sleep 3
-             QFLOW_PIDS=`getDaemonprocs QF_${ID} $DAEMON`
-
-             ## kill all the hanging processes forcefully
-             test "$QFLOW_PIDS" != "" && /bin/kill -9 $QFLOW_PIDS
-        fi
+         ## kill all the hanging processes forcefully
+         test "$QFLOW_PIDS" != "" && /bin/kill -9 $QFLOW_PIDS
     fi
     ;;
 
